sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: jinda111
  redis:
    host: localhost
    port: 6379
  # WeChat配置
  wechat:
    appid: wxe081991316242940
    secret: d320f68cc7451e2dca30d57ca9803ac2
  # 阿里云配置
  alioss:
    endpoint: oss-cn-qingdao.aliyuncs.com
    accessKeyId: LTAI5t5dQfxTJrR3nqYdhSVb
    accessKeySecret: qg9eR3mKl6VGvXxtA5yZh0c5KTyd2I
    bucketName: aliyunofjinda
